import { test, expect } from '@playwright/test';
    
test.beforeEach('Login', async ({ page }) => {
    await page.goto('https://yahshuahris.com/login');
    await page.locator('#email').fill('yahshuauniversity.co@gmail.com');
    await page.locator('#password').fill('K2s3xQY7.XhnHuUajrtU');
    await page.locator('#login-button').click();
    await page.waitForURL('**/dashboard'); // Flexible matcher
});

test('Screening Applicants 4', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.getByRole('link', { name: 'Screen Applicants' }).click();
  await page.getByRole('link', { name: '5 New Applicant/s' }).click();
  await page.getByRole('button', { name: 'Upload Resumes' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.locator('div').filter({ hasText: /^Upload ResumesAdd Stage$/ }).getByRole('button').nth(1).click();
  await page.getByRole('button', { name: 'Withdrawn (0)' }).click();
  await page.locator('div').filter({ hasText: /^Archived Applications$/ }).locator('path').click();
  await page.locator('div').filter({ hasText: /^Archived Applications$/ }).locator('path').click();
  await page.locator('div').filter({ hasText: /^Upload ResumesAdd Stage$/ }).getByRole('button').nth(2).click();
  await page.getByRole('checkbox', { name: 'Not Fit' }).uncheck();
  await page.getByRole('checkbox', { name: 'Good Fit' }).uncheck();
  await page.getByRole('checkbox', { name: 'Ongoing' }).uncheck();
  await page.getByRole('checkbox', { name: 'Passed' }).uncheck();
  await page.getByRole('checkbox', { name: 'Hired' }).uncheck();
  await page.getByRole('checkbox', { name: 'Hired' }).uncheck();
  await page.getByRole('checkbox', { name: 'Passed' }).check();
  await page.getByRole('checkbox', { name: 'Ongoing' }).check();
  await page.getByRole('checkbox', { name: 'Not Fit' }).check();
  await page.getByRole('button', { name: 'Add Stage' }).click();
  await page.getByRole('textbox').filter({ hasText: /^$/ }).press('CapsLock');
  await page.getByRole('textbox').filter({ hasText: /^$/ }).fill('F');
  await page.getByRole('textbox').filter({ hasText: /^$/ }).press('CapsLock');
  await page.getByRole('textbox').filter({ hasText: /^$/ }).fill('Final stage');
  await page.getByRole('button', { name: 'Recommended Applicants Good' }).locator('#edit-job-stage-btn').click();
  await page.getByText('Recommended Applicants').press('CapsLock');
  await page.getByText('Recommended Applicants').fill('F');
  await page.getByText('Recommended Applicants').press('CapsLock');
  await page.getByText('Recommended Applicants').fill('First stage');
  await page.getByRole('button', { name: 'Not Fit (1)', exact: true }).click();
  await page.getByRole('button', { name: 'Stage options' }).first().click();
  await page.getByRole('button', { name: 'Set-up Stage Requirements', exact: true }).click();
  await page.getByRole('textbox', { name: 'Requirements' }).fill('1');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Stage options' }).first().click();
  await page.getByRole('button', { name: 'Assign Users', exact: true }).click();
  await page.getByRole('checkbox', { name: 'YAHSHUA HRIS Demo' }).check();
  await page.getByRole('button', { name: 'Save Assignments' }).click();
  await page.locator('div').filter({ hasText: /^ACAngela Cruz$/ }).getByTestId('elipsis-btn').click();
  await page.getByRole('button', { name: 'View Information', exact: true }).click();
  await page.getByRole('button', { name: 'Job Experience' }).click();
  await page.getByRole('button', { name: 'Summary' }).click();
  await page.getByRole('button', { name: 'Answers' }).click();
  await page.getByRole('button', { name: 'Profile', exact: true }).click();
  await page.getByRole('button', { name: 'View Attached CV/Resume' }).click();
  await page.getByRole('button', { name: 'Go Back to Applicant' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('div').filter({ hasText: /^CFCamille Flores$/ }).getByTestId('elipsis-btn').click();
  await page.getByRole('button', { name: 'Checklist', exact: true }).click();
  await page.getByRole('checkbox', { name: 'AP background' }).check();
  await page.getByRole('checkbox', { name: 'AR background' }).check();
  await page.getByRole('checkbox', { name: 'Knows the basic accounting' }).check();
  await page.getByRole('checkbox', { name: '1' }).check();
  await page.getByRole('textbox', { name: 'Add your notes for this' }).click();
  await page.getByRole('textbox', { name: 'Add your notes for this' }).fill('test');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.locator('div').filter({ hasText: /^ACAngela Cruz$/ }).getByTestId('elipsis-btn').click();
  await page.getByRole('button', { name: 'Checklist', exact: true }).click();
  await page.getByRole('radio', { name: 'Withdrawn' }).check();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('button', { name: 'First stage Good Fit (2) Not' }).getByTestId('elipsis-btn').click();
  await page.getByRole('button', { name: 'First stage Good Fit (2) Not' }).getByTestId('elipsis-btn').click();
  await page.getByRole('textbox', { name: 'Subject*' }).fill('test');
  await page.locator('div').filter({ hasText: /^jreyes@email\.com$/ }).getByRole('button').click();
  await page.locator('div').filter({ hasText: /^CCBCC$/ }).getByRole('textbox').click();
  await page.getByText('Aria Schneider').click();
  await page.locator('.ql-editor').click();
  await page.locator('.ql-editor').fill('test');
  await page.getByRole('button', { name: 'Send' }).click();
  await page.getByRole('button', { name: 'CONTINUE' }).click();
  await page.locator('div').filter({ hasText: /^JRJonathan ReyesHas stage notes$/ }).getByTestId('elipsis-btn').click();
  await page.getByRole('button', { name: 'Schedule Interview', exact: true }).click();
  await page.locator('input[name="date"]').fill('2025-10-21');
  await page.getByRole('textbox', { name: 'Start Time*' }).click();
  await page.getByRole('textbox', { name: 'Start Time*' }).fill('17:10');
  await page.getByLabel('Duration*').selectOption('60');
  await page.getByText('Phone').click();
  await page.locator('.ql-editor').fill('test');
  await page.getByRole('textbox', { name: 'Add hiring team members*' }).fill('zakiorbegoso@gmail.com');
  await page.getByRole('button', { name: 'Send Interview Request' }).click();
  await page.getByRole('button', { name: 'Send Interview Request' }).click();
  await page.getByRole('button', { name: 'Send Interview Request' }).click();
  await page.locator('div').filter({ hasText: /^Schedule Interview$/ }).locator('svg').click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Final stage Good Fit (0) Not' }).click();
  await page.getByRole('button', { name: 'Final Interview Good Fit (1)' }).click();
  await page.getByRole('button', { name: 'Final Interview Good Fit (1)' }).click();
  await page.getByRole('button', { name: 'Stage options' }).nth(2).click();
  await page.getByRole('button', { name: 'Remove Stage', exact: true }).click();
  await page.getByRole('button', { name: 'NO' }).click();
  await page.getByRole('button', { name: 'Stage options' }).nth(3).click();
  await page.getByRole('button', { name: 'Remove Stage', exact: true }).click();
  await page.getByRole('button', { name: 'YES' }).click();
});